#!/bin/zsh
if [[ ! -z $TMUX ]];
then
  tmux rename-window 'live-serv'; tmux set-window-option window-status-current-style 'fg=black bg=orange' ;tmux set-window-option window-status-style 'fg=orange' ; jupyter notebook .
else
  jupyter notebook .
fi
