#!/bin/zsh
if [[ ! -z $TMUX ]];
then
  tmux rename-window 'live-serv'; tmux set-window-option window-status-current-style 'fg=black bg=red' ;tmux set-window-option window-status-style 'fg=red' ; live-server .
else
  live-server .
fi
