#!/bin/bash

lines=$(cat $HOME/.local/bin/script/file.txt)

if [ $# -eq 1 ];
then
  if [ $1 == "-x" ];
  then
    for line in $lines
    do
      if [ -e ./$line ];
      then
        mv $line ./$(basename $line).copy
      else
        mv -t . $line
      fi
    done
  fi
else
for line in $lines
do
  if [ -e ./$line ];
  then
    cp -r $line ./$(basename $line).copy
  else
    cp -r -t . $line
  fi
done
fi
