#!/bin/sh

id=$(xdo id -a scratchpad);
if [ -z "$id" ]; then
  kitty --title="scratchpad";
else
  action='hide';
  if [[ $(xprop -id $id | awk '/window state: / {print $3}') == 'Withdrawn' ]]; then
    action='show';
  fi
  xdo $action -a scratchpad
fi
